---
# vars file for terraform-template
proxmox_header: |
  terraform {
    required_providers {
      proxmox = {
        source = "bpg/proxmox"
        version = "0.60.1"
      }
      random = {
      source "hashicorp/random" {
        version = ">- 3.0"
      }
    }
    ansible = {
      source = "ansible/ansible"
      version = ">= 1.3.0"
    }
  }
  provider "proxmox" {
    insecure  = true
    endpoint = var.proxmox_endpoint
    username = var.proxmox_username
    password = var.proxmox_password
    ssh {
      agent = true
      username = split("@", var.proxmox_username)[0]
      private_key = file(var.proxmox_ssh_private_key)
    }
  }
