---
# tasks file for terraform-template
- name: "Set deployment vars"
  ansible.builtin.set_fact:
    deployments: "{{ lookup('vars', 'deployments') }}"

# - name: "Debug deployment"
#   ansible.builtin.debug:
#     msg: "{{ deployments[deployment].template_name }}"

# - name: "Debug raw template file"
#   ansible.builtin.debug:
#     msg: "{{ lookup('file', (role_path ~ '/templates/' ~ deployments[deployment].template_name)) }}"

- name: "Lookup template for deployment"
  ansible.builtin.set_fact:
    deployment_template: >-
      {{
        lookup(
          'ansible.builtin.template',
          deployments[deployment].template_name,
          template_vars={'deployment_config': deployments[deployment]}
        )
      }}
  delegate_to: localhost

- name: "Template out file"
  ansible.builtin.copy:
    content: "{{ deployment_template }}"
    dest: "~/.test"
    owner: "jharmon"
    mode: "644"
  delegate_to: localhost

- name: "Debug template"
  ansible.builtin.debug:
    msg: "{{ deployment_template }}"
